# Generated by Django 2.2 on 2020-01-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
