# Generated by Django 2.2 on 2020-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artikel_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='isi',
            field=models.TextField(max_length=1000),
        ),
    ]
