# Generated by Django 2.2 on 2020-01-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='gambar',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='gambar',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
