# Generated by Django 2.2 on 2020-01-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
